### PR TITLE
changing default to case insensitive

### PR DESCRIPTION
**Pull request by guenni68**
I'd like to switch the default to case insensitive. It'd require to adjust the tests though ...

### CODE REVIEW

**Comment by princemaple** [comment]
I'm not against it. If the tests could be brought forward, I'll merge right away. Thanks again for the other PR.

**Comment by guenni68** [comment]
Hello Po,


you're either up very early or very late.


Do I understand correctly, you'd like for me to adjust the tests?

**Comment by guenni68** [comment]
Hello Po,


also I think the failing tests may indeed reveal a problem with the case 
insensitive implementation. In particular the "concat" test.


abnf_parsec_test.exs:89:

**Comment by princemaple** [comment]
Yes was late. Sent my reply in bed.

Did you close intentionally?
I will see if I can find some time to take a good look at this onr, this week.

**Comment by guenni68** [comment]
Hello Chen,


yes I did close it intentionally. That one testing issue regarding the 
"concat" stuff may have revealed a flaw in my initial PR.

In short I'm not entirely confident in my own code and want to leave 
things as they are until I've studied the problem further.

So for the time being I thought it best to withdraw my latest PR.

**Comment by princemaple** [comment]
Thanks for being this careful. I'll take another look at the original PR as well, if I get to play with this one.

Have a good day!

P.S. interesting that you switched from "Po" to "Chen". I don't mind either. 🙏

**Comment by guenni68** [comment]
Hello Po,


so sorry for that, it wasn't intentional. It's been a long day and I'm 
still not very familiar with Asian names. Consider it mere sloppiness, 
completely unintentional.

**Comment by princemaple** [comment]
I don't mind either, literally! 😄 
I just found it amusing. No need to apologize!

**Pull request closed without merging**
